### PR TITLE
ENH: support for deblur 1.0.1, and stats output

### PR DESCRIPTION
**Pull request by wasade**
@antgonza these are the changes necessary to fetch the stats output we discussed. The visualization of the stats right now is minimal, and I'm touching up the asset so that it provides the additional context which is presently in the comments in `_format`

### CODE REVIEW

**Comment by wasade** [comment]
Viz brings explorable stats

deblur stats

**Comment by wasade** [comment]
I'm seeing some unexpected numbers right now for reference recruitment. Please do not merge until the issue is understood and addressed.

**Comment by antgonza** [comment]
ok, thanks! Please let us know when ready.

**Comment by wasade** [comment]
It's actually all good. The issue stemmed from the construction of the sample IDs for the q2 import (entirely separate from q2-deblur) which led to a mishandling of the IDs within Deblur itself. I believe this is good to go.

**Comment by antgonza** [comment]
k, thanks for checking and confirming.

**Pull request merged**
